### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by schaar** [moby/practice-repo#1]
**Hello**
- Name: Matt
- Location: SF
- Favorite Obscure 80's singer: Jermaine Stewart 

![image](https://cloud.githubusercontent.com/assets/3597934/6069901/01d8ff6e-ad3d-11e4-87c3-ccd714c33a14.png)

cc: @meentastic @jaw6 @brntbeer @PatrickBM for feedback on my choice of singer (judgey mcjudgerson)

**Comment by meentastic** [comment]
@moby song sample?

**Comment by schaar** [comment]
[Shamblamo!](https://www.youtube.com/watch?v=HWZisnZ-RGE)

**Comment by meentastic** [comment]
> Shamblamo!

whaaa?
